import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      
      <main className={styles.home} >
        <video  autoPlay muted loop  src={"/video/vid_1.mp4"} />
          <Link href="./acceuil">
            <div className={styles.homeButton}> START</div>
          </Link>
      {/* <audio src={"audio/vroum.mp3"} autoPlay loop> </audio> */}

      <h1 className={styles.homeTitre}>Enide For Speed</h1>
      </main> 
      </div>
  )
}
